repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    - id: flake8
    - id: mixed-line-ending
    - id: trailing-whitespace
    - id: requirements-txt-fixer
    - id: name-tests-test
    - id: end-of-file-fixer
default_language_version:
    python: python3
