language: python
python:
  - 3.6
  - 3.7
before_install:
  - pip install -U pip
  - pip install -U pytest
  - pip install pytest-cov
  - pip install codecov
install:
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt
script:
  - py.test --cov-report=term --cov=pyopendatato tests/
after_success:
  - codecov
