language: python
python:
  - 3.6
  - 3.7
before_install:
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
install:
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt
script: pytest
env:
  - CODEDCOV_TOKEN=2d39fe36-b456-408c-a6d4-ba3774aadb20
after_success:
  - codecov
